/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * predict.c
 *
 * Code generation for function 'predict'
 *
 */

/* Include files */
#include "predict.h"
#include "RegressionLinearModel_data.h"
#include "RegressionLinearModel_initialize.h"
#include "RegressionLinearModel_types.h"
#include "rt_nonfinite.h"
#include "rt_nonfinite.h"
#include <math.h>

/* Function Definitions */
double predict(const double X[20])
{
  double b_X;
  double varargout_1;
  int i;
  if (!isInitialized_RegressionLinearModel) {
    RegressionLinearModel_initialize();
  }
  /*  Autogenerated by MATLAB, 09-Jun-2022 10:15:42 */
  /*  Predict Inputs: X */
  b_X = 0.0;
  for (i = 0; i < 20; i++) {
    b_X += X[i] * model.Beta[i];
  }
  varargout_1 = b_X + model.Bias;
  switch (model.ResponseTransform) {
  case Logit:
    varargout_1 = 1.0 / (exp(-varargout_1) + 1.0);
    break;
  case Doublelogit:
    varargout_1 = 1.0 / (exp(-2.0 * varargout_1) + 1.0);
    break;
  case Invlogit:
    if (varargout_1 == 0.0) {
      varargout_1 = rtMinusInf;
    } else if (varargout_1 == 1.0) {
      varargout_1 = rtInf;
    } else if (rtIsNaN(varargout_1)) {
      varargout_1 = rtNaN;
    } else {
      varargout_1 /= 1.0 - varargout_1;
      varargout_1 = log(varargout_1);
    }
    break;
  case Ismax:
    varargout_1 = 1.0;
    break;
  case Sign:
    if (varargout_1 < 0.0) {
      varargout_1 = -1.0;
    } else {
      varargout_1 = (varargout_1 > 0.0);
    }
    break;
  case Symmetric:
    varargout_1 = 2.0 * varargout_1 - 1.0;
    break;
  case Symmetricismax:
    varargout_1 = 1.0;
    break;
  case Symmetriclogit:
    varargout_1 = 2.0 * (1.0 / (exp(-varargout_1) + 1.0)) - 1.0;
    break;
  }
  return varargout_1;
}

/* End of code generation (predict.c) */
