/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * update.c
 *
 * Code generation for function 'update'
 *
 */

/* Include files */
#include "update.h"
#include "RegressionLinear.h"
#include "RegressionLinearModel_data.h"
#include "RegressionLinearModel_initialize.h"
#include "RegressionLinearModel_types.h"
#include "rt_nonfinite.h"

/* Function Definitions */
void update(const struct0_T *varargin_1)
{
  if (!isInitialized_RegressionLinearModel) {
    RegressionLinearModel_initialize();
  }
  /*  Autogenerated by MATLAB, 09-Jun-2022 10:15:42 */
  /*  Update struct fields: Beta */
  /*                        Bias */
  RegressionLinear_update(&model, varargin_1->Beta, varargin_1->Bias);
}

/* End of code generation (update.c) */
