/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * update.c
 *
 * Code generation for function 'update'
 *
 */

/* Include files */
#include "update.h"
#include "CompactRegressionSVM.h"
#include "RegressionSVMModel_data.h"
#include "RegressionSVMModel_types.h"
#include "rt_nonfinite.h"

/* Variable Definitions */
static emlrtRSInfo emlrtRSI = {
    3,        /* lineNo */
    "update", /* fcnName */
    "C:\\nobackup\\_phd_work\\_battery_soh\\_matlab_battery\\_mywork\\_"
    "latest\\ryan4_codeGen\\update.m" /* pathName */
};

static emlrtRSInfo b_emlrtRSI = {
    14,           /* lineNo */
    "initialize", /* fcnName */
    "C:\\nobackup\\_phd_work\\_battery_soh\\_matlab_battery\\_mywork\\_"
    "latest\\ryan4_codeGen\\initialize.m" /* pathName */
};

/* Function Definitions */
void update(const emlrtStack *sp, const struct0_T *varargin_1)
{
  emlrtStack b_st;
  emlrtStack st;
  st.prev = sp;
  st.tls = sp->tls;
  b_st.prev = &st;
  b_st.tls = st.tls;
  /*  Autogenerated by MATLAB, 05-Jun-2022 21:01:47 */
  st.site = &emlrtRSI;
  /*  Autogenerated by MATLAB, 05-Jun-2022 21:01:47 */
  /*  Update struct fields: Alpha */
  /*                        SupportVectors */
  /*                        Scale */
  /*                        Bias */
  b_st.site = &b_emlrtRSI;
  CompactRegressionSVM_update(&b_st, &model, varargin_1->Alpha,
                              varargin_1->SupportVectors, varargin_1->Scale,
                              varargin_1->Bias);
}

/* End of code generation (update.c) */
