/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * update.c
 *
 * Code generation for function 'update'
 *
 */

/* Include files */
#include "update.h"
#include "RegressionLinear.h"
#include "RegressionLinearModel_data.h"
#include "RegressionLinearModel_initialize.h"
#include "RegressionLinearModel_types.h"
#include "rt_nonfinite.h"

#include <stdio.h>
#include "debug.h"


/* Function Definitions */
void update(const struct0_T *varargin_1)
{
  if(DEBUG_LOW) printf("\n==> update");	
  
  if (!isInitialized_RegressionLinearModel) {
    if(DEBUG_LOW) printf("\n isInitialized_RegressionLinearModel -> false ");	
    RegressionLinearModel_initialize();
  }
  /*  Autogenerated by MATLAB, 05-Jun-2022 21:39:25 */
  /*  Update struct fields: Beta */
  /*                        Bias */
  RegressionLinear_update(&model, varargin_1->Beta, varargin_1->Bias);

  if(DEBUG_LOW) printf("\n<-- update");
}

/* End of code generation (update.c) */
